/*
 * generated by Xtext 2.39.0
 */
package iiit.ac.in.smartcitymodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmartCityModelUiModule extends AbstractSmartCityModelUiModule {

	public SmartCityModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
