/*
 * generated by Xtext 2.39.0
 */
package iiit.ac.in.smartcitymodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SmartCityModelStandaloneSetup extends SmartCityModelStandaloneSetupGenerated {

	public static void doSetup() {
		new SmartCityModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
