/*
 * generated by Xtext 2.39.0
 */
package iiit.ac.in.smartcitymodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmartCityModelRuntimeModule extends AbstractSmartCityModelRuntimeModule {
}
