/*
 * generated by Xtext 2.39.0
 */
package iiit.ac.in.smartcitymodel.ide;


/**
 * Use this class to register ide components.
 */
public class SmartCityModelIdeModule extends AbstractSmartCityModelIdeModule {
}
