/*
 * generated by Xtext 2.39.0
 */
package iiit.ac.in.smartcitymodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import iiit.ac.in.smartcitymodel.SmartCityModelRuntimeModule;
import iiit.ac.in.smartcitymodel.SmartCityModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SmartCityModelIdeSetup extends SmartCityModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SmartCityModelRuntimeModule(), new SmartCityModelIdeModule()));
	}
	
}
